spring:
  profiles:
    active: local
    include: oauth # application-xxx.properties 파일을 만들면 xxx 라는 프로파일이 생성된다. oauth 프로파일을 include 하겠다.
  # ??? ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gdsc_timer?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password:

  # JPA ??
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        use_sql_comments: true

  devtools:
    livereload:
      enabled: true # 정적 파일들의 실시간 갱신
  thymeleaf:
    cache: false # thymeleaf 에 대한 캐시를 남기지 않음
    prefix: classpath:/templates/
    suffix: .html
      # Security OAuth
      #  security:
      #    oauth2:
      #      client:
      #        registration:
      #          google:
      #            client-id: 29116814846-j83hn3f2rtr42ug43b941sid7f65c6ii.apps.googleusercontent.com
      #            client-secret: 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
      #            scope:
      #              - email
      #              - profile

      #          kakao:
      #            client-id:
      #            client-secret:

    # Provider ??
#        provider:
#          kakao:
#            authorizationUri: https://kauth.kakao.com/oauth/authorize
#            tokenUri: https://kauth.kakao.com/oauth/token
#            userInfoUri: https://kapi.kakao.com/v2/user/me
#            userNameAttribute: id

# cors ?? -> SecurityConfig.java ??

# jwt secret key ??
#jwt:
#  secret: 'gdsc-timer-hello-world-banana-ice-cream-oreo-chocolate-lol'

# ?? ?? secret key ? Redirect Uri ??
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000 # 30분 1000(1초) * 60 * 30
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect

