spring:
  profiles:
    active: local
  # ??? ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gdsc_timer?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password:

  # JPA ??
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true

  # Security OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 29116814846-678vhg52ne8rklv3n9m1oln4ek2auood.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

#          kakao:
#            client-id:
#            client-secret:

       # Provider ??
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

# cors ?? -> SecurityConfig.java ??

# jwt secret key ??
jwt:
  secret: 'gdsc-timer-hello-world-banana-ice-cream-oreo-chocolate-lol'

# ?? ?? secret key ? Redirect Uri ??
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect

